INSERT INTO GENEROS(NOMBRE) VALUES ('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES ('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES ('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Terror');
